### ISSUE TITLE
Someday, I would like to use tastypie with PostgreSQL

### ISSUE THREAD

**Issue by joshbeckman** [node-tastypie/tastypie-bookshelf#1]
Right now, I think the only thing preventing a postgres backend are some filters hardcoded like this: https://github.com/node-tastypie/tastypie-bookshelf/blob/master/lib/resource/filters/contains.js#L16

**Comment by esatterwhite** [comment]
@andjosh This is in the works

**Comment by esatterwhite** [comment]
@andjosh There is also the issue with bookshelf in general with updating collections or related objects. That was about where I have up. the m2m implementation is goofy

And bookshelf isn't actively being developed anymore. really just bug fixes, so that problem still exists.

**Comment by esatterwhite** [comment]
It is probably doable in a `PUT` situation but you would have to do it in a strict REST fashion and treat the payload as gospel 

meaning, the collection fields would:
- delete the existing relations
- re-create the collection

any thing that is left out of the request payload would be "deleted" from the join table

**Comment by esatterwhite** [comment]
@andjosh I have been looking at [objection](http://vincit.github.io/objection.js), which is built on knex but seems better at being an ORM then bookshelf

Thoughts?

**Comment by joshbeckman** [comment]
I remember seeing objection a _long_ time ago. It seems more robust now, and also I now know all the faults in bookshelf. 

Objection looks like a good idea. It seems to have a much smaller imprint than bookshelf (fewer magic methods, etc), the [validation](http://vincit.github.io/objection.js/#validation) looks useful, and you don't have to drop into a query sub-method/closure to gain access to direct knex query methods.

**Comment by joshbeckman** [comment]
Does it handle updating collections any better than bookshelf?

**Comment by esatterwhite** [comment]
It suggests that it does, but doesn't have a good example
http://vincit.github.io/objection.js/#relation-queries

**Comment by esatterwhite** [comment]
Other orms to note for possible integrations:
- [Sequalize](http://docs.sequelizejs.com/en/latest/)
- [ORM2](http://dresende.github.io/node-orm2/)
- [JS-Data](https://github.com/js-data/js-data)

**Comment by esatterwhite** [comment]
@andjosh all the old [memphis test cases](https://travis-ci.org/node-tastypie/tastypie-bookshelf/builds/148352376) are passing at least

**Comment by esatterwhite** [comment]
@andjosh I published this build to NPM under `@tastypie/bookshelf` if you were looking to use it for something.

Much like bookshelf, it is pretty good at reading. Writing not so much. This is basically `memphis` as we left it.

**Comment by joshbeckman** [comment]
super. Thanks!

I will probably be looking into making a fork for `tastypie-objection/<other orm>` or even `tastypie-knex`. I was talking to people today that just use `knex` instead of one of the other ORMs.

**Comment by esatterwhite** [comment]
@andjosh There is also [squel](https://github.com/hiddentao/squel) and [node-sql-query](https://github.com/dresende/node-sql-query) which are just generic SQL gen. which seems much more flexible than bookshelf.

**Comment by esatterwhite** [comment]
I think I might play around with these weekend
